pyjailhouse: sysfs_parser: Fix IOMMU assignment for PCI bridges
Not only the subdevices need to be assigned to the given IOMMU, also the
bridge itself. Otherwise, the config generator will bail out with
something like

RuntimeError: PCI device 00:03.0 outside the scope of an IOMMU

Signed-off-by: Jan Kiszka <jan.kiszka@siemens.com>